data = {
	'custom_output_ts_avg': 0,
	'logs_indexed_logs_usage_sum_3_day': 0,
	'public_id': '0ff12b775',
	'browser_replay_session_count_sum': None,
	'aws_lambda_func_count': 0,
	'mobile_rum_session_count_android_sum': 0,
	'custom_ts_avg': 0,
	'logs_indexed_logs_usage_sum_15_day': 0,
	'logs_indexed_logs_usage_sum_7_day': 0,
	'uuid': '28d718da-00cc-11ea-a77b-a7797ccb21b4',
	'analyzed_logs_bytes_sum': 0,
	'logs_rehydrated_indexed_logs_usage_sum_3_day': 0,
	'logs_indexed_logs_usage_sum_45_day': 0,
	'profiling_container_agent_count_avg': 0,
	'logs_rehydrated_indexed_logs_usage_sum_15_day': None,
	'logs_rehydrated_indexed_logs_usage_sum_7_day': 0,
	'azure_host_top99p': 0,
	'logs_live_indexed_logs_usage_sum_60_day': 0,
	'logs_rehydrated_indexed_logs_usage_sum_45_day': 0,
	'opentelemetry_host_top99p': 0,
	'logs_live_indexed_logs_usage_sum_180_day': 0,
	'avg_profiled_fargate_tasks': 0,
	'audit_logs_lines_indexed_sum': 0,
	'infra_host_top99p': 0,
	'name': 'Commodity Insights',
	'profiling_host_top99p': 0,
	'alibaba_host_top99p': 0,
	'iot_device_sum': 0,
	'browser_rum_legacy_and_lite_session_count_sum': 0,
	'ci_test_indexed_spans_sum': 0,
	'trace_search_indexed_events_count_sum': 0,
	'cspm_host_top99p': 0,
	'sds_logs_scanned_bytes_sum': 0,
	'apm_host_top99p': 0,
	'logs_rehydrated_indexed_logs_usage_sum_180_day': 0,
	'apm_azure_app_service_host_top99p': 0,
	'logs_live_indexed_logs_usage_sum_360_day': 0,
	'profiling_host_hours_sum': 0,
	'cspm_azure_host_count_sum': 0,
	'dbm_host_sum': 0,
	'logs_indexed_logs_usage_sum_360_day': 0,
	'logs_live_indexed_logs_usage_sum_15_day': 0,
	'logs_rehydrated_indexed_logs_usage_sum_90_day': None,
	'ci_visibility_test_committers_hwm': 0,
	'incident_management_monthly_active_users_hwm': 0,
	'container_avg': 0,
	'logs_indexed_logs_usage_sum_180_day': 0,
	'agent_host_top99p': 0,
	'logs_live_indexed_logs_usage_sum_custom_day': 0,
	'app_sec_host_count_top99p': 0,
	'sds_total_scanned_bytes_sum': 0,
	'ingested_events_bytes_sum': 0,
	'region': 'us',
	'live_indexed_events_sum': 0,
	'custom_input_ts_avg': 0,
	'app_sec_host_count_sum': 0,
	'ci_visibility_pipeline_committers_hwm': 0,
	'live_ingested_bytes_sum': 0,
	'mobile_rum_lite_session_count_sum': 0,
	'snmp_device_top99p': 0,
	'browser_rum_legacy_session_count_sum': 0,
	'cspm_aws_host_count_sum': 0,
	'logs_live_indexed_logs_usage_sum_3_day': 0,
	'apm_fargate_count_avg': 0,
	'dbm_host_top99p': 0,
	'cspm_aws_host_top99p': 0,
	'rehydrated_indexed_events_sum': 0,
	'rum_session_count_sum': 0,
	'observability_pipelines_bytes_processed_sum': 0,
	'mobile_rum_session_count_sum': 0,
	'netflow_indexed_events_count_sum': 0,
	'dbm_queries_avg': 0,
	'rehydrated_ingested_bytes_sum': 0,
	'apm_host_sum': 0,
	'rum_total_session_count_sum': 0,
	'cspm_azure_host_top99p': 0,
	'logs_rehydrated_indexed_logs_usage_sum_custom_day': 0,
	'rum_units_sum': 0,
	'logs_live_indexed_logs_usage_sum_45_day': 0,
	'aws_host_top99p': 0,
	'cws_host_top99p': 0,
	'logs_live_indexed_logs_usage_sum_7_day': 0,
	'mobile_rum_session_count_reactnative_sum': 0,
	'lambda_traced_invocations_count_sum': 0,
	'logs_indexed_logs_usage_sum_90_day': 0,
	'cspm_container_avg': 0,
	'cws_container_count_avg': 0,
	'gcp_host_top99p': 0,
	'fargate_tasks_count_avg': 0,
	'id': '0ff12b775',
	'browser_rum_lite_session_count_sum': 0,
	'logs_rehydrated_indexed_logs_usage_sum_30_day': 0,
	'infra_hours_sum': 0,
	'logs_live_indexed_logs_usage_sum_90_day': 0,
	'logs_live_indexed_logs_usage_sum_30_day': 0,
	'cspm_host_sum': 0,
	'iot_device_top99p': 0,
	'heroku_host_top99p': 0,
	'synthetics_browser_check_calls_count_sum': 0,
	'azure_app_service_top99p': 0,
	'ci_pipeline_indexed_spans_sum': 0,
	'logs_indexed_logs_usage_sum_30_day': 0,
	'cspm_aas_host_top99p': 0,
	'vsphere_host_top99p': 0,
	'indexed_events_count_sum': 0,
	'twol_ingested_events_bytes_sum': 0,
	'synthetics_check_calls_count_sum': 0,
	'logs_rehydrated_indexed_logs_usage_sum_360_day': 0,
	'rum_browser_and_mobile_session_count_sum': 0,
	'logs_indexed_logs_usage_sum_custom_day': 0,
	'npm_host_top99p': 0,
	'cspm_aas_host_count_sum': 0,
	'mobile_rum_session_count_ios_sum': 0,
	'logs_indexed_logs_usage_sum_60_day': 0,
	'online_archive_events_count_sum': 0,
	'aws_lambda_invocations_sum': 0,
	'custom_events_custom_event_count_sum': 0,
	'logs_rehydrated_indexed_logs_usage_sum_60_day': 0,
	'PartitionKey': 'Datadog',
	'RowKey': '4c6b5a38-409f-42c4-aec3-474db22e19cb.03.11.2022',
	'RunDate': '03.11.2022'
}

#reading all values using loop
# for k, v in data.items():
#     print(k, ":", v)

print("data value before removing None")
print(data)

#using this we can also replace the value of those keys
#here aim is to make those 0 whose value is None
for k, v in data.items():
    if "sum" in k or "avg" in k or "count" in k or "top99p" in k or "hwm" in k: #here we notice that key are string and these 4 words - sum, countm top99, hwm, avg covers all key names..so if those values is None then it will make those None to 0 ..
         data[k]  = 0 if not v else v #<if not> interpreter goes inside only when the boolean is None.
    elif isinstance(v, str):
        data[k] = "" if not v else v

print()
print("data value after removing None")
print()
print(data)